# Generated by Django 5.1.7 on 2025-03-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userregistrationmodel_userregistermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='photo',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
