# Generated by Django 5.1.7 on 2025-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userregistermodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='notify',
            field=models.IntegerField(default=0),
        ),
    ]
