# Generated by Django 5.1.7 on 2025-03-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userregistermodel_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='notify',
            field=models.JSONField(default=list),
        ),
    ]
