# Generated by Django 5.1.7 on 2025-03-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userregistermodel_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='notify',
            field=models.JSONField(default=list),
        ),
    ]
