# Generated by Django 5.1.7 on 2025-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userregistermodel_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
