# Generated by Django 5.1.7 on 2025-03-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_transactionmodel_bank_transactionmodel_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='cost',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='income',
            field=models.JSONField(default=list),
        ),
    ]
