# Generated by Django 5.1.7 on 2025-03-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transactionmodel_cost_transactionmodel_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistermodel',
            name='photo',
        ),
    ]
