# Generated by Django 5.1.7 on 2025-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userregistermodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='photo',
            field=models.ImageField(default=' ', upload_to='profile_photos/'),
        ),
    ]
