# Generated by Django 5.1.7 on 2025-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userregistermodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistermodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
