# Generated by Django 5.1.7 on 2025-03-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userregistermodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='OTP',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
